### ISSUE TITLE
Create issues for each feature

### ISSUE THREAD

**Issue by Alonski** [Alonski/realworld-ember#1]
Need to create issues for all the features that need to be in this to comply with the realworld.

**Comment by alexlafroscia** [comment]
Definitely on board! I'll try to go through the list of tasks and see what I can itemize

**Comment by jamesbrewerdev** [comment]
Hey! Just popping over from [gothinkster/realworld](https://github.com/gothinkster/realworld/).

I think this is a really good idea! Gonna talk to @EricSimons about recommending all projects start by creating a Github Project that lists out the features they need to work on. This is also very helpful for us because we can see how far along each project is.

Any progress on this front? Anything we can do to help?

**Comment by Alonski** [comment]
I wanted to create a GitHub project listing all the requirements just haven't gotten around to it.
Making slow progress. With work and school barely have time 😄

**Comment by jamesbrewerdev** [comment]
No worries! Believe me, I know what you mean. :smile:

Why don't you hop in the realworld Gitter channel? http://gitter.im/realworld/main

I'd love to chat and learn more about what we can do to help you as a project creator/maintainer.

**Comment by alexlafroscia** [comment]
I think at this point, we have at least the basic needs scaffolded out. It's hard to itemize everything up front, but I think it's a good start.

**Comment by alexlafroscia** [comment]
This issue was moved to gothinkster/ember-realworld-example-app#1
